version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: restaurantuser
      POSTGRES_PASSWORD: 1410
      POSTGRES_DB: restaurantdb
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurantdb
      SPRING_DATASOURCE_USERNAME: restaurantuser
      SPRING_DATASOURCE_PASSWORD: 1410

volumes:
  postgres-data: