CREATE TABLE IF NOT EXISTS restaurant(
                           id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           city varchar(100) NOT NULL,
                           name varchar(100) NOT NULL,
                           estimated_cost int NOT NULL,
                           average_rating varchar(10) NOT NULL,
                           votes int NOT NULL
);